---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-1.13

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - npm install -g bower codeclimate-test-reporter
  - bower --version
  - npm install phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install
  - bower install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - ember try $EMBER_TRY_SCENARIO test -test-page tests/index.html?hidepassed\&coverage --skip-cleanup
  - CODECLIMATE_REPO_TOKEN=72e46affb8df470fdfcba61cef8f46e76edb6c0b7e4351e73715182e807798af codeclimate-test-reporter < lcov.dat

addons:
  code_climate:
    repo_token: 72e46affb8df470fdfcba61cef8f46e76edb6c0b7e4351e73715182e807798af
